remove the sentence with charter, add FAQ menu, add sidebar blocks, removed unnecessary files
EclipseFdn/lts.eclipse.org pull request #10
Opened 2020-09-10 00:54 UTC by flora8984461

remove the sentence with charter, add FAQ menu, add sidebar blocks, removed unnecessary files

but the sidebar needs some more help,
- cannot get 2 separate blocks, one for "get help", another for "LTS Flyovers", 
- is there a simple way to have one sidebar showing in all pages? Now I am copying paste a lot in config file.

Signed-off-by: Yi Liu <yi.liu@eclipse-foundation.org>

2020-09-10 12:30 UTC, chrisguindon commented
@flora8984461 The logic for the sidebar is located here:
https://github.com/EclipseFdn/hugo-solstice-theme/blob/master/layouts/partials/sidebar.html|

In order to replace or change this behavior, you can copy this file in the layout/partials folder of the lts.eclipse.org and make changes to it.

For example, in this file you can write more logic to include sidebar blocks on all page. Another option is to hardcode these new sidebar block HTML in that file.

2020-09-10 14:53 UTC, flora8984461 commented
> @flora8984461 The logic for the sidebar is located here:
> [https://github.com/EclipseFdn/hugo-solstice-theme/blob/master/layouts/partials/sidebar.html|](https://github.com/EclipseFdn/hugo-solstice-theme/blob/master/layouts/partials/sidebar.html%7C)
> 
> In order to replace or change this behavior, you can copy this file in the layout/partials folder of the lts.eclipse.org and make changes to it.
> 
> For example, in this file you can write more logic to include sidebar blocks on all page. Another option is to hardcode these new sidebar block HTML in that file.

After referring to this, find a workaround.

2020-09-15 20:14 UTC, autumnfound requested changes

2020-09-15 20:14 UTC, autumnfound commented on config.toml
> +#######################
We shouldn't include a comment like this that isn't present in other sites. If we need to split the configs, we can look at doing that as it is [supported by Hugo](https://gohugo.io/getting-started/configuration/#configuration-directory), and we've done it in the Hugo Solstice Theme exampleSite configuration.

2020-09-15 20:14 UTC, autumnfound commented on layouts/partials/sidebar.html
> +      {{ if and (.HasChildren) }}
this can just be `{{ if .HasChildren }}` as there is only one condition

2020-09-16 14:22 UTC, autumnfound approved these changes

2020-09-16 14:38 UTC, merged